name: Deploy
# on a commit push to the gh-pages branch

on:
  release:
    types: [ published ]
    
jobs:
  deploy-to-github-pages:
    # Use ubuntu latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
     
    - name: Setup .NET CORE SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
        
    - name: Install .NET WASM Tools
      run: dotnet workload install wasm-tools
      
    - name: Publish project
      run: dotnet publish ShelterViewer/ShelterViewer.csproj /p:Configuration=Release --output release -p:GHPages=true

      # inject a ga4 script tag into the index.html
    - name: Inject GA4 script tag
      run: |
          GA_SCRIPT_1='<script async src="https://www.googletagmanager.com/gtag/js?id=G-4BVHDFWKPL"></script>'
          GA_SCRIPT_2='<script>window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag("js", new Date()); gtag("config", "G-4BVHDFWKPL");</script>'
          for file in $(find release/wwwroot -name '*.html'); do
            sed "s|</head>|${GA_SCRIPT_1}${GA_SCRIPT_2}</head>|g" "$file"
          done

    - name: create a .version file
      run: 
        echo '{ "version":"${{ github.event.release.tag_name }}" }' > release/wwwroot/.version

    - name: Commit wwwroot to Github Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: release/wwwroot
        force_orphan: true

