name: Deploy
# on a commit push to the gh-pages branch

on:
  release:
    types: [ published ]
    
jobs:
  deploy-to-github-pages:
    permissions:
      contents: read
      pull-requests: write
    # Use ubuntu latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
     
    - name: Setup .NET CORE SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
        
    - name: Install .NET WASM Tools
      run: dotnet workload install wasm-tools
      
    - name: Publish project with version
      run: |
        dotnet publish ShelterViewer.Web.Client/ShelterViewer.Web.Client.csproj \
          /p:Configuration=Release \
          /p:GHPages=true \
          /p:Version=${{ github.event.release.tag_name }} \
          --output release

      # inject a ga4 script tag into the index.html
    - name: Inject GA4 script tag
      uses: jake1164/ga4-ghpages@v1
      with:
        tracking_id: ${{ secrets.GA_TRACKING_ID }}
        file: release/wwwroot/index.html

    - name: Commit wwwroot to Github Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: release/wwwroot
        force_orphan: true

